### ISSUE TITLE
Explore Page UI Improvement

### ISSUE THREAD

**Issue by ojasaklechayt** [ojasaklechayt/NFTic-Marketplace#6]
# Issue
When there are multiple NFT Cards, these cards are aligned vertically.

# Expected 
- For larger screen, there should be 3 cards in one row and then other cards similarly from the next row.
- For Mobile view, all cards should be aligned vertically.

**Comment by 29deepanshutyagi** [comment]
kindly assign me this issue @ojasaklechayt ,i want to work on this issue

**Comment by ojasaklechayt** [comment]
Go for it

**Comment by 12345rams** [comment]
I want to work on this issue.I'm already created pull request and do some change in it.
